language: cpp
os: linux
dist: xenial
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev
      - libstdc++-7-dev
      - libc++-dev
      - libc++-dev
      - build-essential
compiler:
  - clang
  - gcc
os:
  - linux
script:
  - sudo env "PATH=$PATH" cmake -H. -Bbuild
  - cd build && sudo env "PATH=$PATH" cmake --build . --target install
  
