language: cpp
sudo: required
cache:
  apt: true
addons:
apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-all-dev
    - libstdc++-7-dev
    - libc++-dev
    - libc++abi-dev
    - build-essential

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: clang
      
    - os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
            packages:
            - g++-7
            - gcc-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - sudo env "PATH=$PATH" cmake -H. -Bbuild
  - cd build && sudo env "PATH=$PATH" cmake --build . --target install
  
