language: cpp
sudo: required
  
matrix:
  include:
    ## Clang 6.0
    #- env: COMPILER=clang++-6.0
    #  addons: &defaults { apt: { packages: ["clang-6.0", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-6.0"] } }

    # Clang 7.0
    - os: linux
      dist: xenial
      env:
        - MATRIX_EVAL="CXX=clang++"
        - SUDO="sudo env \"PATH=$PATH\""
      addons:  { apt: { packages: ["libc++-dev", "libc++abi-dev", "build-essential", "libstdc++-7-dev", "ccache"], sources: ["ubuntu-toolchain-r-test"] } }
      cache: {apt: true, ccache: true, directories: ["$home/.hunter", "$home/.cppm"]}

    ## GCC 6
    #- env: COMPILER=g++-6
    #  addons: { apt: { packages: ["g++-6", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }

    # GCC 7
    - os: linux
      dist: xenial
      env:
        - MATRIX_EVAL="CXX=g++-7"
        - SUDO="sudo env \"PATH=$PATH\""
      addons: { apt: { packages: ["g++-7", "libc++-dev", "libc++abi-dev", "build-essential", "libstdc++-7-dev", "ccache"], sources: ["ubuntu-toolchain-r-test"] } }
      cache: {apt: true, ccache: true, directories: ["$home/.hunter", "$home/.cppm"]}

    - os: osx
      env: SUDO=""
      #addons: { homebrew: { packages: ["cmake", "ccache"]}}
      osx_image: xcode9.3
      cache: { directories: "$HOME/Library/Caches/Homebrew"}


before_install:
  - eval "${MATRIX_EVAL}"
  - if ["TRAVIS_OS_NAME"=="osx"]; then brew update; fi
  - if ["TRAVIS_OS_NAME"=="osx"]; then brew install cmake; fi
  - if ["TRAVIS_OS_NAME"=="osx"]; then brew install ccache; fi

script:
  - eval "${SUDO}" cmake -H. -Bbuild
  - cd build && eval "${SUDO}" cmake --build . --target install;

