language: cpp
os: linux
dist: xenial
sudo: required
cache:
    apt: true
    ccache: true
addons: &defaults
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libboost-all-dev
        #- libstdc++-7-dev
        - libc++-dev
        - libc++abi-dev
        - build-essential
  
matrix:
  include:
    ## Clang 6.0
    #- env: COMPILER=clang++-6.0
    #  addons: &defaults { apt: { packages: ["clang-6.0", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-6.0"] } }

    # Clang 7.0
    - env: COMPILER=clang++-7.0
      addons:  { apt: { packages: ["clang-7.0", "valgrind"], sources: ["ubuntu-toolchain-r/test", "llvm-toolchain-xenial-7.0"] } }

    ## GCC 6
    #- env: COMPILER=g++-6
    #  addons: { apt: { packages: ["g++-6", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }

    # GCC 7
    - env: COMPILER=g++-7
      addons: { apt: { packages: ["g++-7", "valgrind"], sources: ["ubuntu-toolchain-r/test"] } }

    # Xcode 6.4
    #- os: osx
    #  osx_image: xcode6.4

    ## Xcode 7.3
    #- os: osx
    #  osx_image: xcode7.3

    ## Xcode 8.3
    #- os: osx
    #  osx_image: xcode8.3

    ## Xcode 9.1
    #- os: osx
    #  osx_image: xcode9.1

script:
  - sudo env "PATH=$PATH" cmake -H. -Bbuild
  - cd build && sudo env "PATH=$PATH" cmake --build . --target install
