language: cpp
sudo: required

dist: xenial
addons:
  apt:
    packages:
      - libboost-all-dev
compiler:
  - clang
  - gcc
os:
  - linux
script:
  - sudo cmake -H. -Bbuild
  - cd build && sudo cmake --build . --target install
  
