language: cpp
sudo: required
  
matrix:
  include:
    ## Clang 6.0
    #- env: COMPILER=clang++-6.0
    #  addons: &defaults { apt: { packages: ["clang-6.0", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-xenial-6.0"] } }

    # Clang 7.0
    - os: linux
      dist: xenial
      env:
        - MATRIX_EVAL="CXX=clang++"
        - SUDO="sudo env \"PATH=$PATH\""
      addons:  { apt: { packages: ["libc++-dev", "libc++abi-dev", "build-essential", "libstdc++-7-dev", "ccache"], sources: ["ubuntu-toolchain-r-test"] } }
      cache: {apt: true, ccache: true, directories: ["$home/.hunter", "$home/.cppm"]}

    ## GCC 6
    #- env: COMPILER=g++-6
    #  addons: { apt: { packages: ["g++-6", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }

    # GCC 7
    - os: linux
      dist: xenial
      env:
        - MATRIX_EVAL="CXX=g++-7"
        - SUDO="sudo env \"PATH=$PATH\""
      addons: { apt: { packages: ["g++-7", "libc++-dev", "libc++abi-dev", "build-essential", "libstdc++-7-dev", "ccache"], sources: ["ubuntu-toolchain-r-test"] } }
      cache: {apt: true, ccache: true, directories: ["$home/.hunter", "$home/.cppm"]}

    # Xcode 6.4
    - os: osx
      env: SUDO=""
      addons: { homebrew: { packages: ["cmake", "ccache"]}}
      osx_image: xcode6.4
      cache: { directories: "$HOME/Library/Caches/Homebrew"}

    - os: osx
      env: SUDO=""
      addons: { homebrew: { packages: ["cmake", "ccache"]}}
      osx_image: xcode7.3
      cache: { directories: "$HOME/Library/Caches/Homebrew"}

    - os: osx
      env: SUDO=""
      addons: { homebrew: { packages: ["cmake", "ccache"]}}
      osx_image: xcode8.3
      cache: { directories: "$HOME/Library/Caches/Homebrew"}

    - os: osx
      env: SUDO=""
      addons: { homebrew: { packages: ["cmake", "ccache"]}}
      osx_image: xcode9.1
      cache: { directories: "$HOME/Library/Caches/Homebrew"}

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - "${SUDO}" cmake -H. -Bbuild
  - cd build && "${SUDO}" cmake --build . --target install;
