[package]
name    = "cppm"
version = "1.0.8"
description = "c++ cmake maker use to toml like Cargo"

[cmake]
include  = ["cmake/cppm_install.cmake"]

[[bin]]
name   = "cppm"
source = ["src/.*"]

[test]
source = ["test/.*"]

[dependencies]
cpptoml  = "0.4.0"
fmt      = "6.0.0"
nlpo     = "git"
Catch2   = "2.9.1"
Boost    = {module = "Boost::filesystem", version = "1.58.0", components="system filesystem", hunter=true}
