[package]
    name = "..."
    version = "..."
    desciprtion = "..."
    standard = "{11|14|17(default)|20}" # (optional)
    git = "..." # (optional) this option use to cppm build --export

[hunter] # (optional)  hunter package manager setting option
    use = true|false(default) # if you use hunter package this option is default is true
    url = "..." # (optional) custom hunter version url setting option, [ url, sha1 ] is pair
    sha1 = "..." # (optional) custom hunter version sha1 setting option, [ url, sha1 ] is pair

[cmake] # (optional) cmake setting option 
    include = ["xxx.cmake", ...] # (optional) this option is include cmake file
    version = "..." # (optional) minimum cmake version setting option default is 3.12
    option = "..." # (optional) cmake build option use to command 'cppm build'

# (deprecated) next version
[builder]
    make = {option ="..."}
    ninja = {option ="..."}


[compiler.debug] # (optional) this is only debug mode compiler option
[compiler.release] # (optional) this is only release mode compiler option
[compiler] # (optional) this is debug and release compiler option target compiler is same
    clang = "..." # compiler option
    gcc = "..." # compiler option
    msvc = "..." # compiler option

# (working)
[target.{name}.compiler]
[target.{name}.compiler.debug]
[target.{name}.compiler.release]

[[bin]]
    name = "..." # target name (require)
    sources = ["src/xxx.cpp", ...] # (require)
    install = true(default)|false  # disable install setting
    standard = "{11|14|17(default)|20}"  #(working)

#     
[bin.dependencies]
    ${name} = ${dependency options}
    ${name} = ${dependency options}
# or
dependencies = {
    ${name} = ${dependency options},
    ${name} = ${dependency options},
}

[[lib]]
    name = "..." # target name, export cmake package name 
    type = "static(default)|shared|hearder_only" # (require)
    sources = ["src/xxx.cpp", ...] # use source files, type = "header_only" no nessasery this option
    install = true(default)|false  # disable install setting
    standard = "{11|14|17(default)|20}"  #(working)

# (working) sub project setting
[workspace]
    member = ["path/", "path"]
    
# (working) target classification depedencies add
[target.{name}.dependencies]
# (working)
[target.{name}.platform.{type}.dependencies]
# (working)
[target.{name}.platform.{type}.sources]

# (working)
[[test]]

# (working)
[[example]]

# (working)
[dev-dependencies]

# global dependencies setting option, is same [target.default.platform.default.dependencies] (working)
[dependencies] 
    # cppkg package add dependency
    # name   version(require)
      ... = "x.x.x|git|latest(default)" # latest ordering is x.x.x > git 
    # nomal cmake package add dependency
    # name        (require)                   (optional)           (optional) default is public           
      ... = {module = "..." , version ="...", components="... ...", link_type = "public|private|interface" }
    # hunter package add dependency
    # name        (require)                   (optional)           (optional) default is public            (require) load hunter package
      ... = {module = "..." , version ="...", components="... ...", link_type = "public|private|interface" , hunter= true }
    # none cmake package add dependency
    # name        (require)            (optional)           (optional) default is public (require) none cmake package
      ... = {module = "...", components="... ...", lnk_type = "public|private|interface", no_module= true }
    # module is name that cmake find_package 
    # matched cmake scirpt
    # find_package(${name} ${version} COMPONENTS ${components})
    # target_link_libraries(${target} ${lnk_type} ${modle})

# (working) platform classification depdencies setting 
[platform.windows|macos|linux|unix.dependencies] 

# (working)
[exclude]

# (working)
[ci.github_action]
[ci.appveyer]
[ci.azure]
[ci.travis]
    