[package]
name    = "cppm"
version = "0.1.2"
description = "c++ cmake maker use to toml like Cargo"

[cmake]
version  = "3.10"
#option   = "-DCMAKE_INSTALL_PREFIX=/usr/local"
builder  = "ninja"
compiler = "clang++"
include  = ["cmake/cppm_install.cmake"]

[compiler] 
clang++ = {option = "-std=c++17 -Wall -pthread -fPIC -O0 -g", version = "7.0"}
g++     = {option = "-std=c++17 -Wall -pthread -fPIC -O0 -g", version = "8.0"}

[builder]
ninja   = {option = "-j4"}
make    = {option = "-j4"}

[[bin]]
name   = "cppm"
source = ["src/.*"]

[dependencies]
cpptoml = {cmake = "cpptoml"}
Boost   = {cmake = "${Boost_LIBRARIES}", components="system filesystem"}
nlpo    = {cmake = "nlpo::nlpo"}
fmt     = {cmake = "fmt::fmt"}
