[package]
name    = "cppm"
version = "1.0.2"
description = "c++ cmake maker use to toml like Cargo"
c++-version = "17"

[cmake]
version  = "3.10"
include  = ["cmake/cppm_install.cmake"]
option   = ""

[compiler] 
clang++ = {option = "-Wall -pthread -fPIC -O0 -g"}
g++     = {option = "-Wall -pthread -fPIC -O0 -g"}

[[bin]]
name   = "cppm"
source = ["include/.*", "src/.*"]

[dependencies]
cpptoml  = {module = "cpptoml"}
fmt      = {module = "fmt::fmt"}
nlpo     = {module = "nlpo::nlpo"}
Boost    = {module = "Boost::filesystem", version = "1.58.0", components="system filesystem", hunter=true}
cppfs    = {module = "cppfs::cppfs"}
