[package]
name    = "cppm"
version = "1.0.9"
description = "c++ cmake maker use to toml like Cargo"
git = "https://github.com/injae/cppm.git"

[hunter]
use = true

[cmake]
include  = ["cmake/cppm_install.cmake"]

[[bin]]
name   = "cppm"
source = ["src/.*", "include/.*"]

#[test]
#source = ["test/.*"]

[dependencies]
cpptoml  = "git"
fmt      = "6.0.0"
nlpo     = "git"
md5      = "git"
range-v3 = "0.9.0"