[package]
name    = "cppm"
version = "2.0.0"
description = "c++ cmake maker use to toml like Cargo"

[cmake]
version  = "3.10"
option   = ""
builder  = "ninja"
compiler = "clang++"

[compiler] 
clang++ = {option = "-std=c++17 -Wall -pthread -fPIC -O0 -g", version = "7.0", ccache=true}
g++     = {option = "-std=c++17 -Wall -pthread -fPIC -O0 -g", version = "8.0", ccache=true}

[builder]
ninja   = {option = "-j4"}
make    = {option = "-j4"}

[[bin]]
name   = "cppm"
source = ["include/.*" ,"src/.*"]

[dependencies]
cpptoml = {cmake = "cpptoml"}
Boost   = {cmake = " ${Boost_LIBRARIES}", components="system filesystem"}
fmt     = {cmake = "fmt::fmt"}
nlpo    = {cmake = "nlpo::nlpo"}
