[package]
name    = "cppm"
version = "0.1.0"
description = "c++ cmake maker use to toml like Cargo"

[cmake]
version  = "3.10"
include  = ["cmake/cppm_install.cmake"]
option   = ""

[compiler] 
clang++ = {option = "-std=c++17 -Wall -pthread -fPIC -O0 -g ", version = "7.0"}
g++     = {option = "-std=c++17 -Wall -pthread -fPIC -O0 -g ", version = "7.0"}

[[bin]]
name   = "cppm"
source = ["include/.*", "src/.*"]

[dependencies]
cpptoml = {module = "cpptoml"}
Boost   = {module = "${Boost_LIBRARIES}", version = "1.58.0", components="system filesystem"}
fmt     = {module = "fmt::fmt"}
nlpo    = {module = "nlpo::nlpo"}
