[package]
name    = "cppm"
version = "1.0.8"
description = "c++ cmake maker use to toml like Cargo"
git = "https://github.com/injae/cppm.git"

[cmake]
include  = ["cmake/cppm_install.cmake"]

[[bin]]
name   = "cppm"
source = ["src/.*", "include/.*"]

[test]
source = ["test/.*"]

[dependencies]
cpptoml  = "0.4.0"
fmt      = "6.0.0"
nlpo     = "git"
Boost    = {module = "Boost::filesystem", components="system filesystem", hunter=true}
