[package]
name    = "cppm"
version = "0.0.1"
description = "c++ package manager like Cargo"

[cmake]
version = "3.6"
option  = ""

[compiler] 
clang++ = {option = "-std=c++17 -Wall -pthread -fPIC -O0", version = "7.0", ccache=true}
g++     = {option = "-std=c++17 -Wall -pthread -fPIC -O0", version = "8.0", ccache=true}

[builder]
ninja   = {option = "-j4"}
make    = {option = "-j4"}

[[bin]]
name = "cppm"
source = ["include/.*" ,"src/.*"]

[dependencies]
cpptoml = {cmake = "cpptoml"}
Boost   = {cmake = "boost::filesystem boost::system", components="system filesystem"}
fmt     = {cmake = "fmt::fmt"}
nlpo    = {cmake = "nlpo::nlpo"}
