[package]
name    = "cppm"
version = "1.0.7"
description = "c++ cmake maker use to toml like Cargo"

[feature]

[cmake]
include  = ["cmake/cppm_install.cmake"]

[[bin]]
name   = "cppm"
source = ["src/.*"]

[dependencies]
#cpptoml  = {version="0.4.0"}
cpptoml  = "0.4.0"
fmt      = "5.3.0"
nlpo     = "lastest"
Catch2   = "2.9.1"
Boost    = {module = "Boost::filesystem", version = "1.58.0", components="system filesystem", hunter=true}
