[package]
name    = "cppm"
version = "0.0.13"
description = "c++ cmake maker use to toml like Cargo"
git = "https://github.com/injae/cppm.git"
#tool-version = "dev"

[cmake]
include  = ["cmake/cppm_install.cmake"]

[features]
    default = [ "json", "toml" ] # default flags set ON
    json = ["serdepp/json"]
    toml = ["serdepp/toml11"]
    test = ["$USE_CPPM_TEST"] # default value is OFF
    
[lib]
name = "cppm-core"
type ="header-only"

[[bin]]
name   = "cppm"
source = ["src/.*.cpp"]

[[test]]
name   = "cppm-test-check"
source = ["tests/test.cpp"]

[[example]]
name   = "cppm-core-load"
source = ["examples/example.cpp"]

#[workspace]
#   member = ["libs/hashpp"]

[dependencies]
range-v3 = "git"
nlpo     = "git"
#serdepp  = {version="git", features=[ "xxx" ], default_features=false}
serdepp  = {version="git", link="public", features=["json", "toml"]} 
hash-lib = "git"

[dev-dependencies]
    Catch2 = "2.9.1"

#[target.all-osx-clang.dependencies]
#    dbg-macro = "git"