[package]
name    = "cppm"
version = "0.0.9"
description = "c++ cmake maker use to toml like Cargo"
git = "https://github.com/injae/cppm.git"


[cmake]
include  = ["cmake/cppm_install.cmake"]

[[bin]]
name   = "cppm"
source = ["src/.*", "include/.*"]
install = false

#[test]
#source = ["test/.*"]

[dependencies]
cpptoml  = "git"
fmt      = "6.0.0"
nlpo     = "git"
hashpp   = "git"
#range-v3 = "0.9.0"
reprocxx = "11.0.0"
