[package]
name    = "cppm"
version = "1.0.7"
description = "c++ cmake maker use to toml like Cargo"

[feature]

[cmake]
include  = ["cmake/cppm_install.cmake"]

[compiler] 
clang = {option = "-pthread"}
gcc   = {option = "-pthread"}


[[bin]]
name   = "cppm"
source = ["src/.*"]

[dependencies]
cpptoml  = {module = "cpptoml"}
fmt      = {module = "fmt::fmt"}
nlpo     = {module = "nlpo::nlpo"}
Boost    = {module = "Boost::filesystem", version = "1.58.0", components="system filesystem", hunter=true}

