[package]
name    = "cppm"
version = "1.0.6"
description = "c++ cmake maker use to toml like Cargo"

[cmake]
include  = ["cmake/cppm_install.cmake"]

[compiler.debug] 
clang = {option = "-Wall -pthread -fPIC -O0 -g -std=c++17"}
gcc   = {option = "-Wall -pthread -fPIC -O0 -g -std=c++17"}
msvc  = {option = "/std:c++17 /MP"}
[compiler.release] 
clang = {option = "-pthread -fPIC -O0 -std=c++17"}
gcc   = {option = "-pthread -fPIC -O0 -std=c++17"}
msvc  = {option = "/std:c++17 /MP"}


[[bin]]
name   = "cppm"
source = ["src/.*"]

[dependencies]
cpptoml  = {module = "cpptoml"}
fmt      = {module = "fmt::fmt"}
nlpo     = {module = "nlpo::nlpo"}
Boost    = {module = "Boost::filesystem", version = "1.58.0", components="system filesystem", hunter=true}

