[package]
name    = "cppm"
version = "0.0.13"
description = "c++ cmake maker use to toml like Cargo"
git = "https://github.com/injae/cppm.git"
#tool-version = "dev"

[cmake]
include  = ["cmake/cppm_install.cmake"]

[features]
    default = [ "json", "toml" ] # default flags set ON
    json = ["serdepp/json"]
    toml = ["serdepp/toml11"]
    test = "$USE_CPPM_TEST" # default value is OFF
    
[lib]
name = "cppm-core"
type ="header-only"

[[bin]]
name   = "cppm"
source = ["src/main.cpp",
          "src/cmake/.*",
          "src/core/.*",
          "src/cppkg/.*",
          "src/option/.*",
          "src/cppm_version.h",
          "src/util/.*"]


[[example]]
name   = "cppm-new"
source = ["examples/example.cpp",
          "src/cmake/.*",
          "src/core/.*",
          "src/cppkg/.*",
          "src/options/.*",
          "src/util/.*"]

#[[test]]
#name   = "cppm-test-check"
#source = ["tests/test.cpp"]

[dependencies]
range-v3 = "0.11.0"
nlpo     = "git"
serdepp  = {version="0.1.3", link="public", features=["json", "toml"]} 
hash-lib = "git"
toml11   = "3.7.0"
nlohmann_json = "3.9.1"
fmt = "8.0.1"

[dev-dependencies]
    Catch2 = "2.9.1"
    cpcli    = "git"

#[target.all-osx-clang.dependencies]
#    dbg-macro = "git"