[package]
name    = "cppm"
version = "0.1.3"
description = "c++ cmake maker use to toml like Cargo"

[cmake]
version  = "3.10"
include  = ["cmake/cppm_install.cmake"]
#option   = "-DCMAKE_INSTALL_PREFIX=/usr/local"

[compiler] 
clang++ = {option = "-std=c++17 -Wall -pthread -fPIC -O0 -g", version = "7.0"}
g++     = {option = "-std=c++17 -Wall -pthread -fPIC -O0 -g", version = "7.0"}

[[bin]]
name   = "cppm"
source = ["src/.*"]
install = false

[dependencies]
cpptoml = {cmake = "cpptoml"}
Boost   = {cmake = "${Boost_LIBRARIES}", components="system filesystem"}
fmt     = {cmake = "fmt::fmt"}
nlpo    = {cmake = "nlpo::nlpo"}
