version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - run: brew install cmake
      - run: cmake -H. -Bbuild -G Xcode
      - run: cd build && cmake --build . --target install
