name: Linux

on: [push]

jobs:
  ubuntu-xenial-gcc-11:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@master
      with:
        submodules: true
    - name: C++ Setting
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -yq g++-11 gcc-11 libc++-dev libc++abi-dev build-essential libstdc++-11-dev
    - name: Compiler Setting
      run: |
        echo "CC=gcc-11" >> $GITHUB_ENV
        echo "CXX=g++-11" >> $GITHUB_ENV
    - name: CMake build
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DUSE_CPPM_PATH=ON . && cd build && cmake --build . --target install --target cppm_link 
  ubuntu-xenial-llvm-9:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@master
      with:
        submodules: true
    - name: C++ Setting
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        sudo add-apt-repository -y "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
        sudo apt-get update
        sudo apt-get install -yq clang-9 libc++-dev libc++abi-dev libstdc++-9-dev build-essential
    - name: Compiler Setting
      run: |
        echo "CC=clang-9" >> $GITHUB_ENV
        echo "CXX=clang++-9" >> $GITHUB_ENV
    - name: CMake build
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DUSE_CPPM_PATH=ON . && cd build && cmake --build . --target install --target cppm_link 

