name: Linux

on: [push]

jobs:
  ubuntu-xenial-gcc-10:
    runs-on: ubuntu-16.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@master
      with:
        submodules: true
    - name: C++ Setting
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -yq g++-10 gcc-10 libc++-dev libc++abi-dev build-essential libstdc++-10-dev
    - name: Compiler Setting
      run: |
        echo "CC=gcc-10" >> $GITHUB_ENV
        echo "CXX=g++-10" >> $GITHUB_ENV
    - name: CMake build
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DUSE_CPPM_PATH=ON . && cd build && cmake --build . --target install --target cppm_link 
  ubuntu-xenial-llvm-8:
    runs-on: ubuntu-16.04
    steps:
    - name: Clone Repository
      uses: actions/checkout@master
      with:
        submodules: true
    - name: C++ Setting
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo add-apt-repository -y "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
        sudo apt-get update
        sudo apt-get install -yq clang-8 libc++-dev libc++abi-dev libstdc++-8-dev build-essential
    - name: Compiler Setting
      run: |
        echo "CC=clang-8" >> $GITHUB_ENV
        echo "CXX=clang++-8" >> $GITHUB_ENV
    - name: CMake build
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DUSE_CPPM_PATH=ON . && cd build && cmake --build . --target install --target cppm_link 

