name: MacOS

on: [push]

jobs:
  macos-clang-8:
    runs-on: macos-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@master
    - name: C++ Setting
      run: |
        brew install llvm@8 cmake
    - name: Compiler Setting
      run: |
        echo "::set-env name=CC::clang"
        echo "::set-env name=CXX::clang++"
    - name: CMake build
      run: cmake -Bbuild . && cd build && cmake --build . 


  #  runs-on: macos-latest
  #  strategy:
  #    matrix:
  #      c-compiler: [gcc, clang]
  #      cxx-compiler: [g++, clang++]
  #  steps:
  #  - name: Clone Repository
  #    uses: actions/checkout@master
  #  - name: Compiler Setting
  #    run: echo Compiler Setting
  #    env:
  #      CC: ${{matrix.compiler}}
  #  - name: CMake build
  #    run: cmake -Bbuild . && cd build && cmake --build .
  #  - name: Cppm build install
  #    run: cd build && ./cppm build install
