name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - name: Cloning
      uses: actions/checkout@master
      with:
        path: ./
    - name: Compiler Setting
      run: echo Compiler Setting
      env:
        CC: ${{matrix.compiler}}
    - name: CMake build
      run: cmake -Bbuild .. && cd build && cmake --build .
    - name: Cppm build install
      run: cd build && ./cppm build install
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Cloning
      uses: actions/checkout@master
      with:
        path: ./
    - name: CMake build
      run: cmake -Bbuild .. && cd build && cmake --build .
    - name: Cppm build install
      run: cd build && ./cppm build install
